### ISSUE TITLE
Invalid constant value for assigning a list of tasks

### ISSUE THREAD

**Issue by amirali** [Jamalianpour/time_planner#22]
Hi!
First of all, I'm sooooo new to Flutter. I'm sorry if my question is dumb or anything. I tried to use your library to create a simple weekly calendar based on the example written in the readme file. When I tried to assign the tasks argument, this error has been raised that the tasks list has an invalid constant value.
Can you help me to understand my problem, please?
This is my implementation:
```dart
List<TimePlannerTask> tasks = [
  TimePlannerTask(
    dateTime: TimePlannerDateTime(day: 0, hour: 10, minutes: 0),
    minutesDuration: 90,
  ),
];
@override
Widget build(BuildContext context) {
  return Scaffold(
      appBar: AppBar(title: const Text("Home")),
      body: const Center(
          child: TimePlanner(
        startHour: 6,
        endHour: 23,
        headers: [
          TimePlannerTitle(title: "Saturday"),
          TimePlannerTitle(title: "Sunday"),
          TimePlannerTitle(title: "Monday"),
          TimePlannerTitle(title: "Tuesday"),
          TimePlannerTitle(title: "Wednesday"),
          TimePlannerTitle(title: "Thursday"),
          TimePlannerTitle(title: "Friday"),
        ],
        tasks: tasks, // Here is the error of Invalid constant value.dart(invalid_constant) <-------
      )));
}
```

**Comment by Jamalianpour** [comment]
Hello @amirali 
You put `Timeplanner` in a `Center` widget and set that widget as a const so you can't pass tasks to `Timeplanner` dynamically.
Just remove the `const` keyword and your problem will be solved.
