### ISSUE TITLE
always start from the first day even if i set the day inside TimePlannerDateTime to 1 or 2 or other its always act as if its 0 

### ISSUE THREAD

**Issue by oussama-belmerabet** [Jamalianpour/time_planner#25]
this problem exist only in this version because i try the older one and its work normal

**Comment by oiver12** [comment]
I have the same problem!

**Comment by sedumapps** [comment]
Same problem here

**Comment by sedumapps** [comment]
> I have the same problem!
They have an error in code a workarround to this problem is to set leftSpace to cell width * day.

TimePlannerTask(
            color: Colors.black,
            dateTime: TimePlannerDateTime(day: day, hour: hour, minutes: 0),
            minutesDuration: minutes,
            daysDuration: 1,
            leftSpace:  cellWidth * day.toDouble(),
            onTap: () {},
            child: Text(
              'task',
              style: TextStyle(color: Colors.grey[350], fontSize: 12),
            ),
          )

**Comment by sedumapps** [comment]
BUG at line 52 in time_planner_task.dart 
 left: leftSpace,

FIX:
left: config.cellWidth! * dateTime.day.toDouble() + (leftSpace ?? 0.0),

**Comment by Jamalianpour** [comment]
@sedumapps please open a pull request

**Comment by sedumapps** [comment]
> @sedumapps please open a pull request

sorry, I try but I dont have write access.
