### ISSUE TITLE
Task will not show when creating a task between 12:00 pm and 1:00 am

### ISSUE THREAD

**Issue by martijndormans** [Jamalianpour/time_planner#3]
For some reason a task from 12:00 pm to 1:00am will not show. Do you have any idea why this is??

**Comment by Jamalianpour** [comment]
Hi, thank you for reporting this issue
This problem has been fixed in `0.0.4` version

**Comment by martijndormans** [comment]
Thank you for the quick response, this fixed it indeed. I also fixed it an hour ago by modifying the dateTime of the TimePlannerTask with 1 hour or 0 hour depending on the startdate but this was more a hotfix. So thx again have a great day.
